### ISSUE TITLE
Making output hair-thin

### ISSUE THREAD

**Issue by daphna-kaplan** [X-rayLaser/pytorch-handwriting-synthesis-toolkit#4]
Is there a way to control the thickness of the text? 
I haven't found a parameter for that, but I saw other implementations that did include this option. 
any tips on how hard would it be to implement it and where to start?

**Comment by X-rayLaser** [comment]
You are right. I guess I forgot to add this argument. I am working on it. That should be trivial to do.

**Comment by daphna-kaplan** [comment]
Thank you! I found the relevant change and it is indeed very easy to implement. 
I am also working on adding an "export to svg" option, I will create a request when it's ready. 
By the way, I wanted to thank you personally for the GREAT documentation! I understood the project right away and managed to navigate it easily.

**Comment by X-rayLaser** [comment]
You are welcome! I am glad that you found this project useful. That "export to svg" option sounds good.

**Comment by X-rayLaser** [comment]
I have just pushed the changes. The new optional argument is called thickness. I have also updated the commands section in the Readme file to include this new option.

**Comment by mattlevine32** [comment]
+1 on SVG export @daphna-kaplan, thanks for working on it! I have a use case where I need the SVG output to ideally only be a single SVG <path> strokes (not a filled outline of the letters). i.e the <path> just traces out the exact shape of the letter. Does that happen to be the same as what you're doing?

**Comment by daphna-kaplan** [comment]
@mattlevine32 I just pushed a pr, let's see what the author thinks :) 
I think you can achieve your goal with the .svg export + the new thickness parameter (I have the same need of a single line svg file)

**Comment by X-rayLaser** [comment]
@daphna-kaplan I have viewed the Pull Request. It looks good, but there are 3 tiny fixes required :).
I have left comments near relevant lines describing the issues. Let me know if you have any question.

Once those issues are taken care of, I will happily merge the changes into the main branch. Thank you for your contribution!

**Comment by daphna-kaplan** [comment]
@X-rayLaser Pushed the changes, good calls! thank you :)
